### PR TITLE
Minor fixes to charter text, and remaining issues

### PR DESCRIPTION
**Pull request by duerst**
There are some issues still remaining:
1.    Who can initiate or block task forces (if we aren't careful, we might get lots of proposals, or people who claim they want a task force and we can't deny it)
2.   What will happen with the "previous link" next time the charter is updated? (another problem with moving to github)
3.    It would be good to have a pointer to a list of the specialized mailing lists ("specialised mailing lists for topics such as bidi, indic, cjk, etc") and a pointer to current and past (and maybe potential/planned) task forces

### CODE REVIEW

**Comment by r12a** [comment]
wrt the previous link, it points to the previous charter (ie. the charter that was used for the previous charter period), not the previous version, so is there still an issue there?

i added pointers to lists of mailing lists and task forces to the charter (and updated those in the target destinations).

**Comment by duerst** [comment]
Hello Richard,

On 2016/01/15 22:33, r12a wrote:

> wrt the previous link, it points to the previous charter (ie. the charter that was used for the previous charter period), not the previous version, so is there still an issue there?

Sorry I wasn't explicit enough. The question was: Given we are not 
currently using a dated link for the new charter, how will we link to 
the previous charter when we will be writing a new charter in 2 years or so?

Regards,   Martin.

**Comment by r12a** [comment]
thanks for the clarification. My plan was to create a copy of the current charter page when a new charter period starts, and name that copy charter2016.html.  The new charter which would then be created would then point to charter2016.html for information. This makes life easier in general, since <groupname>/charter always points to the current charter, and there's no need to guess at the year etc.  It will hopefully make it easier to find older charters in future.

**Comment by duerst** [comment]
@r12a: that sounds like a plan. Is this how W3C in general does things now, or just i18n-specific? It would be good to have some W3C-wide alignment on such issues.

**Pull request merged**
