### PR TITLE
Update the Unicode character template to match specdev and tr-design

### PR DESCRIPTION
**Pull request by xfq**

### CODE REVIEW

**Comment by xfq** [comment]
Current page: https://www.w3.org/International/i18n-activity/guidelines/editing

The preview doesn't work, because it refers to styles and scripts in another repo using relative path.

**Review by aphillips — APPROVED** [review]

**Comment by r12a** [comment]
Although the preview doesn't work, have you carefully checked that the rendered page with changes applied is identical to the original?

**Comment by xfq** [comment]
> Although the preview doesn't work, have you carefully checked that the rendered page with changes applied is identical to the original?

They are different, because the font size was changed from `85%` to `0.75em`.

**Comment by r12a** [comment]
Right. But does everything otherwise look ok?

**Comment by xfq** [comment]
Yes. Here's a screenshot:

unicode

**Review by r12a — APPROVED** [review]

**Pull request merged**
