### PR TITLE
moved past FTF to list of past FTF

### PR DESCRIPTION
**Pull request by himorin**
(for issue #613)

### CODE REVIEW

**Comment by r12a** [comment]
Good try 👍  but we do expect to meet in Fukuoka at the next TPAC. Could you change that?

**Comment by himorin** [comment]
ah, yes. totally forgot about next TPAC...
also is it better to have a link to [agenda](https://www.w3.org/International/wiki/2018TPACAgenda) and two minutes [10/22](https://www.w3.org/2018/10/22-i18n-minutes.html), [10/23](https://www.w3.org/2018/10/23-i18n-minutes.html)?

**Comment by r12a** [comment]
Yes, good to add links to minutes, thanks.  I didn't do it in the past due to lack of time.  However, dates like "11/6" are potentially confusing (i18n issue!).  Can you change the dates to "6 Nov", and so on?

**Review by r12a — APPROVED** [review]

**Comment by r12a** [comment]
Thanks !

**Comment by himorin** [comment]
sorry that I failed to leave message on issue. Yes, date format shall be easily distinguishable, and modified as suggested.
let me merge PR and close issue.

**Pull request merged**
